services:
  terraform-gcp-practice-app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=flask_db
      - DB_HOST=cloudsql-proxy
    volumes:
      - ../:/terraform-gcp-practice-app
    depends_on:
      - cloudsql-proxy
