version: '3.8'

services:
  terraform-gcp-practice-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    env_file: ../deployment/.env
    environment:
      - USE_CONNECTOR=false
      - DB_USER=terraform_project
      - DB_PASSWORD=supersecretpassword
      - DB_NAME=terraformprojectdatabase
      - DB_HOST=cloudsql-proxy
      - FLASK_DEBUG=true
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json
    volumes:
      - ../:/terraform-gcp-practice-app
      - ../gcp-creds.json:/secrets/key.json:ro
    depends_on:
      cloudsql-proxy:
        condition: service_healthy
    networks:
      - mynetwork

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.6-buster
    command:
      - "/cloud_sql_proxy"
      - "-ip_address_types=PRIVATE"
      - "-instances=terraform-practice-250806:asia-east1:terraformprojectinstancedb=tcp:0.0.0.0:3306"
      - "-credential_file=/secrets/key.json"
    volumes:
      - ../gcp-creds.json:/secrets/key.json:ro
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 6<>/dev/tcp/localhost/3306"]
      interval: 3s
      timeout: 3s
      retries: 5

networks:
  mynetwork:
