version: '3.8'
services:
  flask-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
