version: '3.8'
services:
  terraform-gcp-practice-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST)/$(DB_NAME)
      - PORT=5000
      - DB_USER=flask
      - DB_PASSWORD=your_password
      - DB_NAME=flask_db
      - DB_HOST=127.0.0.1  # If Cloud SQL Proxy, change proxy addrress
    volumes:
      - ../:/terraform-gcp-practice-app
    depends_on:
      - cloudsql-proxy

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.6
    command:
      - "/cloud_sql_proxy"
      - "-instances=${INSTANCE_CONNECTION_NAME}=tcp:3306"
      - "-credential_file=/config/key.json"
    volumes:
      - ../gcp-creds.json:/config/key.json:ro
