version: '3.8'
services:
  terraform-gcp-practice-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - FLASK_DEBUG=true
    volumes:
      - ../:/terraform-gcp-practice-app
    depends_on:
      - cloudsql-proxy
    networks:
      - mynetwork

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.6
    command:
      - "/cloud_sql_proxy"
      - "-ip_address_types=PUBLIC"
      - "-instances=terraform-practice-250806:asia-east1:flask-db-instance=tcp:0.0.0.0:3306"
      - "-credential_file=/config/key.json"
    volumes:
      - ../gcp-creds.json:/config/key.json:ro
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
