name: infra-workflow

on:
  push:
    branches: [master]
    paths:
    - 'deployment/terraform/**'
    - '.github/workflows/00_infra.yml'
  workflow_dispatch: {}

concurrency:
  group: infra-${{ github.ref }}
  cancel-in-progress: false

jobs:
  infra-setting:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup-google-cloud-credential
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: install-google-cli
        uses: google-github-actions/setup-gcloud@v1
      - name: install-terraform
        uses: hashicorp/setup-terraform@v3
      - name: terraform-init
        run: make run-terraform-init
      - name: terraform-fmt
        run: make run-terraform-fmt
      - name: terraform-validate
        run: make run-terraform-validate
      - name: terraform-import
        run: make run-terraform-import-all
      - name: terraform-plan
        run: make run-terraform-plan
      - name: build-and-push-docker-image-to-artifact-registry
        run: make run-docker-push-to-artifact-registry
      - name: terraform-apply
        run: make run-terraform-apply
