name: ci-workflow

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup-google-cloud-credential
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: install-google-cli
        uses: google-github-actions/setup-gcloud@v1
      - name: install-terraform
        uses: hashicorp/setup-terraform@v3
      - name: terraform-init
        run: make run-terraform-init
      - name: terraform-fmt
        run: make run-terraform-fmt
      - name: terraform-validate
        run: make run-terraform-validate