name: Deploy to GCP

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  IMAGE_NAME: flask-api

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/flask-repo/${{ env.IMAGE_NAME }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/flask-repo/${{ env.IMAGE_NAME }}

      - name: Terraform Apply
        working-directory: deployment/terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var="db_user=root" \
            -var="db_password=password" \
            -var="db_name=flask_db" \
            -var="vpc_network=projects/${{ env.PROJECT_ID }}/global/networks/default" \
            -var="image_url=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/flask-repo/${{ env.IMAGE_NAME }}"
